### PR TITLE
Update release.yml

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
## Related Issues

Resolves https://github.com/h3poteto/whalebird-desktop/issues/3777

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
cc @h3poteto

**Comment by h3poteto** [comment]
It looks like the same logic has been moved to the release job. Does it resolve the error?
I'm not sure what the cause of the error is. 
https://github.com/h3poteto/whalebird-desktop/actions/runs/3402630176/jobs/5658591894

**Comment by vedantmgoyal2009** [comment]
The release artifacts are published "after" the release is published, and the actions runs immediately as soon as release is created. Hence, it cannot find any binaries, thus failing to create PR.

**Comment by h3poteto** [comment]
Oh, I see. Thank you!

**Review by h3poteto — APPROVED** [review]

**Pull request merged**
