### PR TITLE
Upstreaming flatpak data

### PR DESCRIPTION
**Pull request by Lunarequest**
## Description

I am upstream flatpak specific files to this repo, flathub would prefer is metainfo file and desktop file were kept upstream.

### CODE REVIEW

**Comment by h3poteto** [comment]
I'm not sure why these files should be kept in this repository. Is there any document?

**Comment by Lunarequest** [comment]
These are normally kept upstream. With other build systems these can be used but electron-builder currently doesn't support this

**Comment by h3poteto** [comment]
I think that you've already created these files in your repository: https://github.com/Lunarequest/whalebird-flatpak/blob/mistress/social.whalebird.WhalebirdDesktop.desktop 
Isn't that enough?

**Comment by Lunarequest** [comment]
The flathub folks would like it upstreamed

**Comment by h3poteto** [comment]
I see, it is about this discussion: https://github.com/flathub/flathub/pull/2641#discussion_r751082392
I wanted to know this context.

**Pull request merged**
