### PR TITLE
Add Traditional Chinese in i18n

### PR DESCRIPTION
**Pull request by xatier**

### CODE REVIEW

**Comment by xatier** [comment]
@h3poteto: please enable Traditional Chinese in crowdin. Thanks!

**Comment by h3poteto** [comment]
I added zh-TW in crowdin, so an empty translation file is created. Please rebase, tests may be passed.

**Comment by xatier** [comment]
@h3poteto rebased against upstream, please take a look.

**Comment by xatier** [comment]
All translation done. :D 

https://crowdin.com/project/whalebird/zh-TW

**Review by h3poteto — APPROVED** [review]
Thank you

**Pull request merged**
