### PR TITLE
Update translation.json

### PR DESCRIPTION
**Pull request by IzNoGud78**
## Description
Added missing translations.

### CODE REVIEW

**Comment by h3poteto** [comment]
Please confirm json format.

**Comment by h3poteto** [comment]
Tests are failed.
Don't accept duplicate key definition between `translation.json` and `translation.missing.json`.

**Comment by h3poteto** [comment]
Thank you for your improving, but I can't merge it until tests are succeeded.
Please check duplicated keys in `translation.json` and `translation.missing.json`.

**Comment by IzNoGud78** [comment]
$ dnf info nodejs
`Name: nodejs
Epoca: 1
Version: 12.13.0
Rilascio : 7.fc31
Architecture: x86_64
Size: 412 k
Source: nodejs-12.13.0-7.fc31.src.rpm`

$ npm --version
`6.10.3`

$ npm audit
`[...] found 8 vulnerabilities (2 low, 2 moderate, 4 high) in 508905 scanned packages
run `npm audit fix` to fix 6 of them.
2 vulnerabilities require manual review. See the full report for details.`

$ npm run spec
[https://pastebin.com/raw/gvt1tWHr](url)

$ cat /home/_user_/.npm/_logs/2019-11-15T16_35_27_703Z-debug.log
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'spec' ]
2 info using npm@6.10.3
3 info using node@v12.10.0
4 verbose run-script [ 'prespec', 'spec', 'postspec' ]
5 info lifecycle Whalebird@3.0.0~prespec: Whalebird@3.0.0
6 info lifecycle Whalebird@3.0.0~spec: Whalebird@3.0.0
7 verbose lifecycle Whalebird@3.0.0~spec: unsafe-perm in lifecycle true
8 verbose lifecycle Whalebird@3.0.0~spec: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/paco/whalebird-desktop/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/home/paco/bin:/usr/local/sbin:/usr/sbin
9 verbose lifecycle Whalebird@3.0.0~spec: CWD: /home/paco/whalebird-desktop
10 silly lifecycle Whalebird@3.0.0~spec: Args: [ '-c', 'NODE_ENV=test jest -u --maxWorkers=3' ]
11 silly lifecycle Whalebird@3.0.0~spec: Returned: code: 1  signal: null
12 info lifecycle Whalebird@3.0.0~spec: Failed to exec spec script
13 verbose stack Error: Whalebird@3.0.0 spec: `NODE_ENV=test jest -u --maxWorkers=3`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid Whalebird@3.0.0
15 verbose cwd /home/paco/whalebird-desktop
16 verbose Linux 5.3.11-300.fc31.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "spec"
18 verbose node v12.10.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error Whalebird@3.0.0 spec: `NODE_ENV=test jest -u --maxWorkers=3`
22 error Exit status 1
23 error Failed at the Whalebird@3.0.0 spec script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

$ npm run dev
[https://pastebin.com/raw/DS8pw8mw](url)

however, on my PC it seems to work fine.

**Comment by h3poteto** [comment]
I fixed and re-created a pull request for this change: #1105

**Pull request closed without merging**
